#!/bin/sh

VBOX_ADDITIONS=${BASEDIR}/VBoxLinuxAdditions.run

aptitude -y install wget
wget -O ${VBOX_ADDITIONS} 'http://debian.heebs.ch/d-i/VBoxLinuxAdditions.run'
chmod +x ${VBOX_ADDITIONS}
aptitude -y purge wget

aptitude -y install build-essential linux-headers-$(uname -r)
${VBOX_ADDITIONS} --nox11
aptitude -y purge build-essential linux-headers-$(uname -r)

rm ${VBOX_ADDITIONS}
