#!/bin/sh

rm -rf /root/.aptitude
rm -rf /root/.cache
rm -f  /root/.bash_history
rm -rf /root/vagrant-setup*

rm -rf /var/log/*
(cd /var/log ; touch lastlog wtmp ; chown root:utmp lastlog wtmp ; chmod 664 lastlog wtmp)


passwd << EOT
vagrant
vagrant
EOT

passwd vagrant << EOT
vagrant
vagrant
EOT

rm $0
