#!/bin/sh

DEBIAN_FRONTEND=noninteractive
DEBIAN_PRIORITY=low
export DEBIAN_FRONTEND DEBIAN_PRIORITY

aptitude -y remove \
    -o DPkg::Options::=--force-confdef \
    -o DPkg::Options::=--force-confold \
    resolvconf ppp pppconfig
