#!/bin/sh

cd $(dirname $0)
BASEDIR=$(pwd -P)

HOSTNAME=vagrant-$(lsb_release -is | tr A-Z a-z)-$(lsb_release -cs)
echo ${HOSTNAME} > /etc/hostname
hostname ${HOSTNAME}
cat > /etc/hosts << EOF
127.0.0.1	localhost
127.0.1.1	${HOSTNAME}

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOF

add_vagrant_keys () {
    mkdir -p ${1}/.ssh
    cd ${1}/.ssh
    cp ${BASEDIR}/keys/vagrant .
    cp ${BASEDIR}/keys/vagrant.pub .
    cp vagrant.pub authorized_keys
    chmod u=rwx,go= .
    chmod u=r,go= ./vagrant
    chown -R ${2}:${2} .
}

add_vagrant_keys /root         root
add_vagrant_keys /home/vagrant vagrant
