#!/bin/sh

BASEDIR=$(dirname $0)
PASS=${1}
PASSLIST=${BASEDIR}/pass-${PASS}.list

if [ ! -f ${PASSLIST} ]; then
    echo "no list for pass ${PASS}"
    exit 1
fi

for script in $(cat ${PASSLIST}) ; do
    echo ----- ${script} -----
    ${BASEDIR}/run ${script}
done
