#!/bin/sh

BASEDIR=$(dirname $0)
PASS=${1}

if [ ${PASS} != '1' -a ${PASS} != '2' ]; then
    echo 'please specify pass 1 or 2'
    exit 1
fi

for script in ${BASEDIR}/pass_${PASS}-* ; do
    echo ----- ${script} -----
    ${script}
done
